# video link: https://www.youtube.com/watch?v=Poc0X5fS9us&list=PL98nY_tJQXZln8spB5uTZdKN08mYGkOf2&index=2

In [14]:

import torch

In [15]:
torch.__version__

'1.9.0+cu102'

In [16]:
a = torch.tensor([5.], requires_grad=True)
b = torch.tensor([6.], requires_grad=True)   #  calculating the gradient of a point automatically

In [17]:
a

tensor([5.], requires_grad=True)

In [18]:
b

tensor([6.], requires_grad=True)

In [19]:
y = a**3 - b**2

In [20]:
y

tensor([89.], grad_fn=<SubBackward0>)

In [21]:
# dy/da = 3*a**2 = 75
# dy/db = -2b = -12

In [23]:
print(a.grad)

None


In [24]:
y.backward()

In [25]:
a.grad

tensor([75.])

In [26]:
b.grad

tensor([-12.])

In [27]:
W = torch.randn(10,1 , requires_grad=True)
b = torch.randn(1 , requires_grad=True)

In [28]:
W

tensor([[ 1.2735],
        [-2.8289],
        [-1.3373],
        [-1.3052],
        [ 0.2014],
        [-0.6397],
        [ 0.4779],
        [-0.0031],
        [-0.0506],
        [ 0.4229]], requires_grad=True)

In [29]:
b

tensor([0.4483], requires_grad=True)

In [30]:
X = torch.rand(1,10)

In [31]:
X

tensor([[0.3096, 0.9142, 0.0697, 0.1416, 0.1029, 0.0601, 0.6198, 0.2672, 0.6514,
         0.3041]])

In [32]:
output = torch.matmul(X,W) + b

In [33]:
output

tensor([[-1.6483]], grad_fn=<AddBackward0>)

In [34]:
loss = 1 - output

In [35]:
loss

tensor([[2.6483]], grad_fn=<RsubBackward1>)

In [37]:
loss.backward()

In [38]:
W.grad

tensor([[-0.3096],
        [-0.9142],
        [-0.0697],
        [-0.1416],
        [-0.1029],
        [-0.0601],
        [-0.6198],
        [-0.2672],
        [-0.6514],
        [-0.3041]])

In [39]:
b.grad

tensor([-1.])

In [40]:
lr = 0.01

In [41]:
with torch.no_grad():
  W = W - 0.01 * W.grad.data

In [42]:
W

tensor([[ 1.2766e+00],
        [-2.8197e+00],
        [-1.3366e+00],
        [-1.3037e+00],
        [ 2.0241e-01],
        [-6.3915e-01],
        [ 4.8405e-01],
        [-3.9351e-04],
        [-4.4045e-02],
        [ 4.2596e-01]])