In [1]:
!nvidia-smi

Sat Mar  5 06:37:06 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P8    32W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
import torch

In [6]:
t1 = torch.tensor(2)
t1

tensor(2)

In [7]:
t1.dtype

torch.int64

In [ ]:
#vectors
t2 = torch.tensor([1,2,3,45,5])
t2

tensor([ 1,  2,  3, 45,  5])

In [ ]:
t2.dtype

torch.int64

In [ ]:
#matrix
t3 = torch.tensor([
                   [2,3,4],
                   [3,5,6]])
t3

tensor([[2, 3, 4],
        [3, 5, 6]])

In [ ]:
t3.ndim

2

In [ ]:
t4 = torch.tensor([
     [[11,23,45],
      [23,34,45]],
     [[55,66,77],
      [45,34,34]]])

t4

tensor([[[11, 23, 45],
         [23, 34, 45]],

        [[55, 66, 77],
         [45, 34, 34]]])

In [ ]:
t4.ndim

3

In [ ]:
print(t1.shape)
print(t2.shape)
print(t3.shape)
print(t4.shape)

torch.Size([])
torch.Size([5])
torch.Size([2, 3])
torch.Size([2, 2, 3])


In [ ]:
# Tensors Operation
x = torch.tensor(3.)
w = torch.tensor(2. , requires_grad=True)
b = torch.tensor(7. , requires_grad=True)
x,w,b

(tensor(3.), tensor(2., requires_grad=True), tensor(7., requires_grad=True))

In [ ]:
y = w * x + b
y

tensor(13., grad_fn=<AddBackward0>)

In [ ]:
y.backward()

In [ ]:
print(w.grad)
print(x.grad)
print(b.grad)

tensor(3.)
None
tensor(1.)


In [ ]:
# Tensor function
t6 = torch.full((2,2), 55)
t6

tensor([[55, 55],
        [55, 55]])

In [ ]:
t7 = torch.cat((t6,t6))
t7

tensor([[55, 55],
        [55, 55],
        [55, 55],
        [55, 55]])

In [ ]:
t9 = t7.reshape(2,4)
t9

tensor([[55, 55, 55, 55],
        [55, 55, 55, 55]])

In [ ]:
# interoperabity with numpy
import numpy as np

x = np.array([[23,44,55], [55,67,88]])
x

array([[23, 44, 55],
       [55, 67, 88]])

In [ ]:
y = torch.from_numpy(x)
y.dtype

torch.int64

In [ ]:
y = y.numpy()
y.dtype

dtype('int64')

In [ ]:
a = torch.tensor([[2.,3],
                  [4,5]], requires_grad=True)
b = torch.tensor(3. , requires_grad=True)

x = torch.tensor([[6,3],
                  [4.,2]])

d = torch.tensor(4. , requires_grad=True)

In [ ]:
y = b * d

In [ ]:
y

tensor(12., grad_fn=<MulBackward0>)

In [ ]:
y.backward()

In [ ]:
print(a.grad)
print(b.grad)
print(x.grad)

None
tensor(4.)
None
