In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [4]:
ar = np.array(l)

In [5]:
ar

array([1, 2, 3, 4])

In [6]:
type(ar)

numpy.ndarray

In [7]:
np.array([[1,2] ,[3,4]])

array([[1, 2],
       [3, 4]])

In [8]:
np.asarray(l)

array([1, 2, 3, 4])

In [9]:
a= [2,3,4]

In [10]:
np.asanyarray(a)

array([2, 3, 4])

In [11]:
b = np.matrix(l)

In [12]:
b

matrix([[1, 2, 3, 4]])

In [13]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [14]:
a = np.array(l)

In [15]:
a


array([1, 2, 3, 4])

In [17]:
c = a  

In [18]:
c

array([1, 2, 3, 4])

In [19]:
a

array([1, 2, 3, 4])

In [21]:
c[0] = 100

In [22]:
c

array([100,   2,   3,   4])

In [23]:
a

array([100,   2,   3,   4])

In [24]:
d = np.copy(a)

In [25]:
d

array([100,   2,   3,   4])

In [26]:
a

array([100,   2,   3,   4])

In [27]:
a[1] = 400

In [28]:
a

array([100, 400,   3,   4])

In [29]:
d

array([100,   2,   3,   4])

In [30]:
np.fromfunction(lambda i, j : i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [31]:
np.fromfunction(lambda i, j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [33]:
iterable = (i*i for i in range(5))

In [35]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [36]:
np.fromstring('234 234' , sep= ' ')

array([234., 234.])

In [37]:
np.fromstring('4,5' , sep= ',')

array([4., 5.])

In [38]:
#Numpy - Data Types.

In [39]:
l = [2,3,4,5,6]

In [40]:
ar = np.array(l)

In [41]:
ar

array([2, 3, 4, 5, 6])

In [42]:
ar.ndim

1

In [43]:
ar2 = np.array([[1,2,3,4] , [2,3,4,5]])

In [44]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [45]:
ar2.ndim

2

In [46]:
ar.size

5

In [47]:
ar2.size

8

In [48]:
ar

array([2, 3, 4, 5, 6])

In [49]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [50]:
ar.shape

(5,)

In [52]:
ar2.shape

(2, 4)

In [53]:
ar.dtype

dtype('int64')

In [54]:
ar2.dtype


dtype('int64')

In [55]:
ar22 = np.array([(1.4,45,45) , (23,45,66)])

In [56]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [57]:
ar22.dtype

dtype('float64')

In [59]:
list(range(5))

[0, 1, 2, 3, 4]

In [60]:
list(range(0.1 ,5))

TypeError: 'float' object cannot be interpreted as an integer

In [61]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [63]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [65]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [66]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [67]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [68]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [70]:
ar4 = np.zeros((3,4,2,3))

In [72]:
ar4.ndim


4

In [73]:
ar4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [74]:
np.ones(4)

array([1., 1., 1., 1.])

In [75]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [77]:
on =np.ones((2,3,2))

In [79]:
on + 5


array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [80]:
on *4


array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [84]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [86]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [87]:
np.linspace(2,4 , 20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [89]:
np.logspace(2,5 , 10, base = 2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [91]:
arr = np.random.randn(3,4)

In [92]:
import pandas as pd 

In [93]:
pd.DataFrame(arr)

0         1         2         3
0  0.890713 -0.553569 -1.960728 -0.434195
1  1.135963  1.900850  0.105555 -0.956539
2  0.657613 -0.023822 -0.113005 -0.246385

In [94]:
np.random.rand(3,4)

array([[0.55841232, 0.45863676, 0.99992056, 0.34681312],
       [0.85335992, 0.58281617, 0.39651828, 0.01454947],
       [0.60889145, 0.69353235, 0.3229714 , 0.90551562]])

In [98]:
pd.DataFrame(np.random.randint(1,110 , (300,400))).to_csv('test.csv')

In [99]:
arr = np.random.rand(3,4)

In [100]:
arr

array([[0.85591307, 0.14990179, 0.77019389, 0.9530107 ],
       [0.79286516, 0.82718965, 0.61247144, 0.73040623],
       [0.41905299, 0.02473037, 0.42774325, 0.1323675 ]])

In [103]:
arr.reshape(6,-1)

array([[0.85591307, 0.14990179],
       [0.77019389, 0.9530107 ],
       [0.79286516, 0.82718965],
       [0.61247144, 0.73040623],
       [0.41905299, 0.02473037],
       [0.42774325, 0.1323675 ]])

In [105]:
arr1 = arr.reshape(6,-134353553435)

In [106]:
arr1

array([[0.85591307, 0.14990179],
       [0.77019389, 0.9530107 ],
       [0.79286516, 0.82718965],
       [0.61247144, 0.73040623],
       [0.41905299, 0.02473037],
       [0.42774325, 0.1323675 ]])

In [109]:
arr1[1][1]

0.9530106973492012

In [112]:
arr1[2:5,1]

array([0.82718965, 0.73040623, 0.02473037])

In [115]:
arr = np.random.randint(1,100 , (5,5))

In [116]:
arr

array([[20, 83, 37, 56, 55],
       [78, 48, 72, 14, 28],
       [68, 49, 86, 75, 89],
       [91, 52, 13, 37, 33],
       [51, 43, 36, 50, 32]])

In [119]:
arr[arr>50]

array([83, 56, 55, 78, 72, 68, 86, 75, 89, 91, 52, 51])

In [120]:
arr

array([[20, 83, 37, 56, 55],
       [78, 48, 72, 14, 28],
       [68, 49, 86, 75, 89],
       [91, 52, 13, 37, 33],
       [51, 43, 36, 50, 32]])

In [121]:
arr[2:4 , [1,2]]

array([[49, 86],
       [52, 13]])

In [124]:
arr[0][0] = 5000

In [125]:
arr

array([[5000,   83,   37,   56,   55],
       [  78,   48,   72,   14,   28],
       [  68,   49,   86,   75,   89],
       [  91,   52,   13,   37,   33],
       [  51,   43,   36,   50,   32]])

In [127]:
arr1 = np.random.randint(1,3 , (3,3))
arr2 = np.random.randint(1,3 , (3,3))

In [128]:
arr1

array([[2, 2, 1],
       [2, 1, 2],
       [1, 2, 1]])

In [129]:
arr2


array([[1, 2, 2],
       [2, 1, 1],
       [1, 1, 1]])

In [130]:
arr1+arr2

array([[3, 4, 3],
       [4, 2, 3],
       [2, 3, 2]])

In [131]:
arr1-arr2

array([[ 1,  0, -1],
       [ 0,  0,  1],
       [ 0,  1,  0]])

In [132]:
arr1/arr2

array([[2. , 1. , 0.5],
       [1. , 1. , 2. ],
       [1. , 2. , 1. ]])

In [133]:
arr1 * arr2

array([[2, 4, 2],
       [4, 1, 2],
       [1, 2, 1]])

In [134]:
arr1

array([[2, 2, 1],
       [2, 1, 2],
       [1, 2, 1]])

In [135]:
arr2

array([[1, 2, 2],
       [2, 1, 1],
       [1, 1, 1]])

In [136]:
arr1@arr2

array([[7, 7, 7],
       [6, 7, 7],
       [6, 5, 5]])

In [137]:
arr1/0

/tmp/ipykernel_103/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [139]:
arr1 +100

array([[102, 102, 101],
       [102, 101, 102],
       [101, 102, 101]])

In [140]:
arr1**2

array([[4, 4, 1],
       [4, 1, 4],
       [1, 4, 1]])

In [141]:
#Numpy – Broadcasting.

In [144]:
arr =np.zeros((4,4))

In [145]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [147]:
row = np.array([1,2,3,4])

In [152]:
row.shape



(4,)

In [149]:
arr + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [153]:
row.T

array([1, 2, 3, 4])

In [154]:
col = np.array([[1,2,3,4]])

In [157]:
col.T + arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [156]:
col

array([[1, 2, 3, 4]])

In [158]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [160]:
arr1 = np.random.randint(1,4 , (3,4))

In [161]:
arr1

array([[2, 2, 3, 2],
       [1, 1, 3, 3],
       [1, 1, 1, 2]])

In [162]:
np.sqrt(arr1)

array([[1.41421356, 1.41421356, 1.73205081, 1.41421356],
       [1.        , 1.        , 1.73205081, 1.73205081],
       [1.        , 1.        , 1.        , 1.41421356]])

In [163]:
np.exp(arr1)

array([[ 7.3890561 ,  7.3890561 , 20.08553692,  7.3890561 ],
       [ 2.71828183,  2.71828183, 20.08553692, 20.08553692],
       [ 2.71828183,  2.71828183,  2.71828183,  7.3890561 ]])

In [164]:
np.log10(arr1)

array([[0.30103   , 0.30103   , 0.47712125, 0.30103   ],
       [0.        , 0.        , 0.47712125, 0.47712125],
       [0.        , 0.        , 0.        , 0.30103   ]])